services:
  db:
    container_name: haarken-db
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - project.env

  web:
    container_name: haarken-web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/app/web
      - staticfiles:/home/app/web/staticfiles
      - mediafiles:/home/app/web/media
    ports:
      - "8000"
    expose:
      - 8000
    env_file:
      - project.env
    depends_on:
      - db

  broker:
    container_name: haarken-broker
    image: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  celery_worker:
    container_name: haarken-worker
    restart: always
    build:
      context: .
    command: celery -A core worker --loglevel=INFO
    depends_on:
      - broker

  nginx:
    container_name: haarken-nginx
    image: nginx:mainline-alpine
    restart: always
    ports:
      - "1337:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - staticfiles:/home/app/web/staticfiles
      - mediafiles:/home/app/web/media

volumes:
  postgres-data:
  staticfiles:
  mediafiles:
